### ISSUE TITLE
yard is in conflict with nodejs

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/peertube_ynh#13] opened 2018-04-02 15:50 UTC
i just tried an install using : 
`yunohost app install https://github.com/YunoHost-Apps/peertube_ynh/tree/testing`

but it failed : 
```
Attention : dpkg: concernant yarn_1.5.1_all.deb contenant yarn :
Attention :  yarn entre en conflit avec nodejs (<< 4.0.0)
Attention :   « nodejs » (version « 0.10.29~dfsg-2 ») est présent ainsi que « installé ».
Attention : 
Attention : dpkg: erreur de traitement de l'archive yarn_1.5.1_all.deb (--install) :
Attention :  paquets en conflit - yarn non installé
Attention : Des erreurs ont été rencontrées pendant l'exécution :
Attention :  yarn_1.5.1_all.deb
Attention : !!
Attention :   peertube's script has encountered an error. Its execution was cancelled.
Attention : !!
```
tell me if you need a full log, i can reproduce it ;)

```
yunohost -v
yunohost: 
  repo: stable
  version: 2.7.10
yunohost-admin: 
  repo: stable
  version: 2.7.7
moulinette: 
  repo: stable
  version: 2.7.7
ssowat: 
  repo: stable
  version: 2.7.7
```

**Comment by anmol26s** [comment] 2018-04-03 07:56
I think the the nodejs should be installed first then yarn should be installed.
Can you install the nodejs 8 first manually and then try to install the app ? 
Thanks for your help.

**Comment by isAAAc** [comment] 2018-04-03 21:33
nodejs is already installed :/ : 
```
 # aptitude search nodejs
i   nodejs                                                                                 - evented I/O for V8 javascript                                                                    
v   nodejs-abi-46                                                                          -                                                                                                  
p   nodejs-dbg                                                                             - evented I/O for V8 javascript (debug)                                                            
i A nodejs-dev                                                                             - evented I/O for V8 javascript (development files)                                                
i   nodejs-legacy                                                                          - evented I/O for V8 javascript (legacy symlink) 
```

**Comment by isAAAc** [comment] 2018-04-03 21:50
the complete log of failed install ;) (sorry, my $LANG=Fr) :   https://krashboyz.org/zerobin/?8a4e0f6c7fc9adb9#aaWhUOLVU+ntevNsflXU7jsDL0N/N3E/X4CwLpHHXrg=

**Comment by isAAAc** [comment] 2018-04-04 01:04
```
nodejs -v
v0.10.29
```
damned, my version is very old !
i'm a bit affraid to break my yunohost if i do that no ?

**Comment by anmol26s** [comment] 2018-04-04 06:05
Your version is old. Nodejs is used by some apps like mastodon,etc. But you should update it for security and compatibility.
I have changed the script to install nodejs before yarn. It should update your nodejs to latest stable release.
Hope it works this time.

**Comment by isAAAc** [comment] 2018-04-04 09:55
ok , updated via : 
` curl -sL https://deb.nodesource.com/setup_8.x | bash -`
then : 
`apt-get install nodejs`
now i have : 
```
#  nodejs -v
v8.11.1
```
i retry the install of peertube

**Comment by isAAAc** [comment] 2018-04-04 10:07
ok, 
install failed, for another reason, do you want i open a new issue ? (but i dont understand what's happend)
https://krashboyz.org/zerobin/?7775556869005112#y2VM329uOxoeJrZWpk5AD8R6CRsKTdmX+XzexGF2QGA=

**Comment by anmol26s** [comment] 2018-04-04 13:15
The installation was successful,but mail sent to you was failed.
Can you replace YOUR_EMAIL with your email and  tell me output of : 
 
`echo "test" | mail -a "Content-Type: text/plain; charset=UTF-8" -s "peertube was installed" -t "YOUR_EMAIL"`
 and
`echo "test" | mail -a "Content-Type: text/plain; charset=UTF-8" -s "☁️🆈🅽🅷☁️: peertube was installed" -t "YOUR_EMAIL"`

**Comment by isAAAc** [comment] 2018-04-04 15:01
```
echo "test" | mail -a "Content-Type: text/plain; charset=UTF-8" -s "peertube was installed" -t "isaaac@krashboyz.org"
Content-Type: text/plain; charset=UTF-8: Aucun fichier ou dossier de ce type
```
-> nothing
for the second command is broken some character are emotes ^^

**Comment by anmol26s** [comment] 2018-04-04 15:15
Is mailutils installed? If not this should fix it.
`sudo apt-get install mailutils`

**Comment by isAAAc** [comment] 2018-04-04 15:38
ok, mailutils just installed, 
first command still gives no answer, 
i try a new peertube intall (tree testing)
`little esaylistening music during the install `
install failed again :/
i try the first command again, and still nothing :/

**Comment by anmol26s** [comment] 2018-04-04 15:56
You can try this commit .This don't have the option to send password in the email, so you will have to enter the password while installation . Keep the password simple as you can change it in admin panel : 
`yunohost app install  --verbose https://github.com/YunoHost-Apps/peertube_ynh/tree/a4df2d28c5adfbb989160001458f8e9a9d54ace8
`
This error is something to do with UTF-8 error while sending the mail. You can try to install it with locals.
Sending of admin email is done by @Jibec . Maybe he can correct it.

**Comment by anmol26s** [comment] 2018-04-04 20:33
@Jibec log is here https://krashboyz.org/zerobin/?7775556869005112#y2VM329uOxoeJrZWpk5AD8R6CRsKTdmX+XzexGF2QGA=

**Comment by Jibec** [comment] 2018-04-04 20:40
OK, interesting indeed, what kind of server is it? Raspbian up to date?

**Comment by isAAAc** [comment] 2018-04-05 06:51
`yunohost app install --verbose https://github.com/YunoHost-Apps/peertube_ynh/tree/a4df2d28c5adfbb989160001458f8e9a9d54ace8`

-> installation is done and working, i can load the webpage @ media.krashboyz.org
BUT
i can't login with mail-adress and password i selected during the install :/

@Jibec : hi, it's a VPS @ gandi

If mailutils is needed , it should be checked during the install , and installed if it's not already installed on the system, shouldn't it ?
@anmol26s : same with the nodejs ? perhaps adding the command i used to upgrade my nodejs ?

**Comment by anmol26s** [comment] 2018-04-05 11:49
The default username is **root**. There is some other issue with the command sending the email to you which is still not clear. The latest version of nodejs would be installed with the command. If mailutils is added in the Yunohost dependency then its not required to be added in the app's dependency.

**Comment by isAAAc** [comment] 2018-04-05 11:59
i still cant log in with root / <password i entered during peertube install>
:/

**Comment by isAAAc** [comment] 2018-04-05 13:11
ok, well, it failed on first attempt : 
```
root@krashboyz:/var/www/peertube# NODE_ENV=production npm run reset-password -- -u root

> peertube@1.0.0-beta.3 reset-password /var/www/peertube
> node ./dist/scripts/reset-password.js "-u" "root"

module.js:678
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/var/www/peertube/node_modules/bcrypt/lib/binding/bcrypt_lib.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 59. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:678:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/peertube/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peertube@1.0.0-beta.3 reset-password: `node ./dist/scripts/reset-password.js "-u" "root"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peertube@1.0.0-beta.3 reset-password script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-05T13_00_29_528Z-debug.log
```
then i used `npm rebuild` but still have the same error , so i tried `npm install`

the command to change the password of peertube root user works now, 
but i still can't log in with root/the_new_password  :/

**Comment by anmol26s** [comment] 2018-04-05 13:28
That is strange. Can you clear your cache of browser and try?

**Comment by isAAAc** [comment] 2018-04-05 13:32
\o/ i restarted nginx and F5, 
i'm loged on !
thx a lot for your help, 
issue is done for me, 
tell me if you want i make some other tests , or you can close the issue ;)

**Comment by anmol26s** [comment] 2018-04-05 13:39
Yes. can you tell me output of `locale -a`? I still don't understand the cause of the error in the testing branch.

**Comment by anmol26s** [comment] 2018-04-05 13:42
I am closing  the issue for now. If someone have same issue please reopen the issue.

**Closed** 2018-04-05 13:42 UTC

**Comment by isAAAc** [comment] 2018-04-06 11:30
```
admin@krashboyz:~$ locale -a
bs_BA.utf8
C
cs_CZ.utf8
C.UTF-8
da_DK.utf8
de_AT.utf8
de_DE.utf8
el_GR.utf8
en_CA.utf8
en_GB.utf8
en_US.utf8
es_ES.utf8
fi_FI.utf8
fr_FR.utf8
hr_HR.utf8
hu_HU.utf8
hy_AM.utf8
id_ID.utf8
it_IT.utf8
ja_JP.utf8
ko_KR.utf8
nl_NL.utf8
pl_PL.utf8
POSIX
pt_BR.utf8
ro_RO.utf8
ru_RU.utf8
sr_RS@latin.UTF-8
sr_RS.utf8
sr_RS.utf8@latin.UTF-8
vi_VN.utf8
zh_CN.utf8
```
