### ISSUE TITLE
sso logged into Yunohost peertube 2.1.1 "Cannot load more videos. Try again later.

### ISSUE THREAD

**Issue by plslvval** [YunoHost-Apps/peertube_ynh#161] opened 2020-04-04 12:49 UTC
What happened?

I upgraded peertube 2.1.0 on yunohost working instance to 2.1.1.
Within Linux Firefox 74.0 and logged wihtin yunohost instance no video can been seen, thumbnails appears only for "discover' and any other option shows red notification
'Erreur

Cannot load more videos. Try again later.'

What do you expect to happen instead?

This is working when not logged in yunohost instance.

Steps to reproduce:

Log in serveur.slv-valbonne.fr instance
Connect to https://peertube.serveur.slv-valbonne.fr/videos/local

server traces shows authentication header errors only when used with firefox :

avril 04 14:10:48 serveur.slv-valbonne.fr peertube[20404]: [peertube.serveur.slv-valbonne.fr:443] 2020-04-04 14:10:48.594 warn: Cannot authenticate. {
avril 04 14:10:48 serveur.slv-valbonne.fr peertube[20404]: "err": {
avril 04 14:10:48 serveur.slv-valbonne.fr peertube[20404]: "statusCode": 400,
avril 04 14:10:48 serveur.slv-valbonne.fr peertube[20404]: "status": 400,
avril 04 14:10:48 serveur.slv-valbonne.fr peertube[20404]: "code": 400,
avril 04 14:10:48 serveur.slv-valbonne.fr peertube[20404]: "message": "Invalid request: malformed authorization header",
avril 04 14:10:48 serveur.slv-valbonne.fr peertube[20404]: "name": "invalid_request",
avril 04 14:10:48 serveur.slv-valbonne.fr peertube[20404]: "stack": "invalid_request: Invalid request: malformed authorization header\n at new InvalidRequest (/var/www/peertube/node_modules/oauth2-server/lib/errors/invalid-request-error.js:26:14)\n at AuthenticateHandler.getTokenFromRequestHeader (/var/www/peertube/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:146:11)\n at AuthenticateHandler.getTokenFromRequest (/var/www/peertube/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:121:17)\n at AuthenticateHandler. (/var/www/peertube/node_modules/oauth2-server/lib/handlers/authenticate-handler.js:68:19)\n at AuthenticateHandler.tryCatcher (/var/www/peertube/node_modules/oauth2-server/node_modules/bluebird/js/release/util.js:16:23)\n at Promise._settlePromiseFromHandler (/var/www/peertube/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:512:31)\n at Promise._settlePromise (/var/www/peertube/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:569:18)\n at Promise._settlePromiseCtx (/var/www/peertube/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:606:10)\n at Async._drainQueue (/var/www/peertube/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:138:12)\n at Async._drainQueues (/var/www/peertube/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:143:10)\n at Immediate.Async.drainQueues [as _onImmediate] (/var/www/peertube/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:17:14)\n at runCallback (timers.js:705:18)\n at tryOnImmediate (timers.js:676:5)\n at processImmediate (timers.js:658:5)"
avril 04 14:10:48 serveur.slv-valbonne.fr peertube[20404]: }
avril 04 14:10:48 serveur.slv-valbonne.fr peertube[20404]: }

**Comment by plslvval** [comment] 2020-04-04 12:51
I initialy openned a peertube issue since it appears with upgrade : https://github.com/Chocobozzz/PeerTube/issues/2599

**Comment by artlog** [comment] 2020-04-04 14:00
i guess  "skipped_urls" configuration of ssowat were changed. ssowat configuration is documented here https://github.com/YunoHost/SSOwat

**Comment by gnouts** [comment] 2020-04-05 09:41
I can confirm this bug. It's not related to the browser. But only if you are connected to the sso or not.
(I think you should edit the title, btw)

And it might be related to this bug https://github.com/YunoHost-Apps/peertube_ynh/issues/119.
Though, this bug is old and my problem only appears with ynh 3.7 upgrade.
And I have the url under "skipped_urls" in `/etc/ssowat/conf.json.persistent` (because it used to be necessary for this https://forum.yunohost.org/t/yunohost-peertube-et-yunohost-probleme-de-jetons-didentification/4571/3)

**Comment by plslvval** [comment] 2020-04-05 15:49
thanks @gnouts , like you i have my url in "skipped_urls" in /etc/ssowat/conf.json.persistent too, it seems it it either disregarded or overriden by other  /etc/ssowat/conf.json

**Comment by plslvval** [comment] 2020-04-05 16:00
i have my url added by upgrade ( or install too i guess ) into unprotected_urls, what is affected by sso as docuemnted in ssowat project.

unprotected_urls List of URLs and/or URIs that will not be affected by SSOwat unless user is authenticated

i have it in skipped_url too in persistent, i tried to move it for persistent to json.conf but it does nothing more, then when you have same url in unprotected and skipped, unprotected wins, so to fix it i had to remove it from etc/ssowat/conf.json. This will be lost at next update...
i think it lacks a way in persistent configuration to have negative entries meaning : remove it if exists...

**Comment by plslvval** [comment] 2020-04-05 16:24
@gnouts yes it is surely related to this bug #119.
i then guess that pending fix for #119 which to add url as noauth will fix it.
I am still not sure why this bug did pop up at upgrade while i really think i didn't hit it before.

**Comment by plslvval** [comment] 2020-04-05 17:02
well, after review i had a syntax error in my /etc/ssowat/conf.json.persistent : 

    "skipped_urls" : [
         "peertube.serveur.slv-valbonne.fr"
    }
closing '[' with '}'

**Comment by gnouts** [comment] 2020-04-06 07:40
lol I'm disapointed. In my case I don't have a syntax error. I run a json parser on the config file and I still have the error. Pretty sure it wasn't there before v3.7.
I'll keep digging, as it seems I'm now the only one with this bug ^^'

**Comment by yalh76** [comment] 2020-04-06 18:17
I reopened it, But no time for now to solve it. Need to know if you are the only one or if there are others peerube_ynh wih the same issue

**Comment by plslvval** [comment] 2020-04-08 08:40
@gnouts i closed it too quickly, problem reappears even with 
 "skipped_urls" : [
         "peertube.serveur.slv-valbonne.fr"
    ]   
within /etc/ssowat/conf.json.persistent

when i am logged in yunohost portal.

**Comment by plslvval** [comment] 2020-04-08 09:06
@gnouts i edited /etc/ssowat/json.conf and removed my peertube url from "unprotected_urls" and keeping "skipped_urls" in  /etc/ssowat/conf.json.persistent
this fixes my problem, i guess it will reappear soon since conf.json should not be manually edited

**Comment by plslvval** [comment] 2020-04-08 09:18
behavior change comes from this commit in SSOwat : https://github.com/YunoHost/SSOwat/commit/eb2872d5ed5eab8b797f1da3dc5ec5def801dac2#diff-80c7526357cd62e0d0b6d80c34850105

so it appears in debian/3.7.0.3 while it was not in debian/3.7.0.2 

this means that unprotected url will override skipped url if they are of the same length or longer.

**Comment by gnouts** [comment] 2020-04-08 09:48
Good catch ! I can confirm the workaround.
Though,next time this command will run, you'll loose your change : `sudo yunohost app ssowatconf`
(Which is everytime you edit a domain, a user or an app, lol)

**Comment by yalh76** [comment] 2020-04-08 10:32
> 
> 
> behavior change comes from this commit in SSOwat : [YunoHost/SSOwat@eb2872d#diff-80c7526357cd62e0d0b6d80c34850105](https://github.com/YunoHost/SSOwat/commit/eb2872d5ed5eab8b797f1da3dc5ec5def801dac2#diff-80c7526357cd62e0d0b6d80c34850105)
> 
> so it appears in debian/3.7.0.3 while it was not in debian/3.7.0.2
> 
> this means that unprotected url will override skipped url if they are of the same length or longer.
Good catch. Can you open an issue at https://github.com/YunoHost/issues with all the needed informations ?

**Comment by plslvval** [comment] 2020-04-08 16:59
@yalh76 i am not sure this change is wrong, i guess it was done on purpose this changes order of priority between conflcting requests, still i will open an issue to trigger a discussion on that topic.

**Comment by plslvval** [comment] 2020-04-08 17:12
Then as github did it automagically https://github.com/YunoHost/issues/issues/1552 is the one @yalh76 requested.
Thing in ssowat is that it does not always prioritize persistent above autogenerated in general.

**Comment by jhammons** [comment] 2020-06-10 03:05
You can work around this issue for the time being, if you have a public instance, by commenting out the two "lua"-containing lines of /etc/nginx/conf.d/<domain.tld>.conf and then run `/etc/init.d/nginx reload` ... Perhaps this might help someone.

**Comment by stemy2** [comment] 2020-06-22 19:20
Same issue, and i can't login because of an error message: "Invalid client: client is invalid". If i logout from YNH, it works again.

**Comment by rosbeef** [comment] 2020-08-05 19:33
It seems the same error as mastodon when https://3cmr.fr/yunohost/sso/ is connected some apps can not connect : https://github.com/YunoHost-Apps/mastodon_ynh/issues/6

**Comment by plslvval** [comment] 2020-09-27 09:04
> Same issue, and i can't login because of an error message: "Invalid client: client is invalid". If i logout from YNH, it works again.

yep 

i did comment this line : "include conf.d/yunohost_panel.conf.inc;"
that deactivates yunohost web integration within this domain.

and restarted nginx with
sudo systemctl restart nginx

fine thanks !

**Comment by plslvval** [comment] 2020-09-30 16:45
Well problems still occurs and this is related to SSOwAuthUser cookie added by yunhost.
This is a specific case where my peertube domain is a subdomain of my yunohost domain where i log in.
in my case peertube is here : https://peertube.serveur.slv-valbonne.fr/ and yunhost server is https://serveur.slv-valbonne.fr/
whenever i log in serveur.slv-valbonne.fr some SSOwAuthxxx cookies is addded and those are recongined by javascript scripts on client claiming ... a problem.
So this is ... complicated now.
I can't change my peertube domain since it is federated and it is difficult to change yunohost one too ...

**Comment by yalh76** [comment] 2020-10-01 01:04
> 
> 
> Well problems still occurs and this is related to SSOwAuthUser cookie added by yunhost.
> This is a specific case where my peertube domain is a subdomain of my yunohost domain where i log in.
> in my case peertube is here : https://peertube.serveur.slv-valbonne.fr/ and yunhost server is https://serveur.slv-valbonne.fr/
> whenever i log in serveur.slv-valbonne.fr some SSOwAuthxxx cookies is addded and those are recongined by javascript scripts on client claiming ... a problem.
> So this is ... complicated now.
> I can't change my peertube domain since it is federated and it is difficult to change yunohost one too ...

Yes same issue as: https://github.com/YunoHost-Apps/peertube_ynh/issues/119 => related to https://github.com/YunoHost/issues/issues/1420, will be solved by https://github.com/YunoHost/yunohost/pull/861

**Comment by deckname** [comment] 2020-12-19 21:36
Just wanted to say that I have this issue with peertube and mastodon as well and that I have used [this fix (comment out two access_by_lua lines)](https://github.com/YunoHost-Apps/peertube_ynh/issues/161#issuecomment-641691887) for a long time now.

**Comment by yalh76** [comment] 2021-01-06 00:23
should be solved when 4.1 will be released

**Closed** 2021-03-07 00:10 UTC
Labels: bug
