### ISSUE TITLE
Unable to connect when logged on YNH

### ISSUE THREAD

**Issue by stemy2** [YunoHost-Apps/peertube_ynh#182] opened 2020-08-07 16:43 UTC
**Describe the bug**
I can't login when i'm logged on yunohost, it fails with the message "invalid client: client is invalid".
**Versions**
- Hardware: *Desktop PC*
- YunoHost version: 4.0.3
- I have access to my server: *Full*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: *no*
- Using, or trying to install package version/branch: master
**To Reproduce**

   1. *Login to the yunohost portal '...'*
   2. *Go to own peertube instance*
   3. *Try to login*

**Expected behavior**
I can connect without being obligated to disconnect from YNH.

**Comment by yalh76** [comment] 2020-08-07 16:51
Duplicate of https://github.com/YunoHost-Apps/peertube_ynh/issues/119

**Closed by yalh76** 2020-08-07 16:51 UTC
