### ISSUE TITLE
flatmap-stream was removed, breaking installation

### ISSUE THREAD

**Issue by Jibec** [YunoHost-Apps/peertube_ynh#61] opened 2018-11-30 21:52 UTC
because of the famous npm issue, flatmap-stream was removed from npm: https://github.com/hugeglass/flatmap-stream/issues/2
PeerTube reacted: https://github.com/Chocobozzz/PeerTube/issues/1432

Of course, the package installation is broken.
Long life to npm...

> 112297 DEBUG yarn install v1.12.3
> 112800 DEBUG [1/5] Validating package.json...
> 112801 DEBUG [2/5] Resolving packages...
> 113606 WARNING warning Resolution field "@types/bluebird@3.5.21" is incompatible with requested version "@types/bluebird@3.5.18"
> 115214 DEBUG [3/5] Fetching packages...
> 117622 DEBUG info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> 117622 WARNING error https://registry.yarnpkg.com/flatmap-stream/-/flatmap-stream-0.1.0.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
> 117623 DEBUG + ynh_exit_properly
> 117624 WARNING !!
> 117624 DEBUG + local exit_code=1
> 117625 WARNING   peertube's script has encountered an error. Its execution was cancelled.
> 117626 DEBUG + '[' 1 -eq 0 ']'
> 117626 WARNING !!
> 117627 DEBUG + trap '' EXIT
> 117627 WARNING 
> 117628 DEBUG + set +eu
> 117629 DEBUG + echo -e '!!\n  peertube'\''s script has encountered an error. Its execution was cancelled.\n!!'
> 117629 DEBUG + type -t ynh_clean_setup
> 117630 DEBUG + ynh_die
> 117631 DEBUG + echo ''
> 117631 DEBUG + exit 1
> 117752 INFO L’opération « Installer l’application « peertube » » a échouée ! Pour avoir de l’aide, merci de partager le log de cette opération en utilisant la commande « yunohost log display 20181130-224558-app_install-peertube --share »

**Comment by estebanborai** [comment] 2018-12-05 23:56
Deleting the `yarn.lock` file and running `yarn` then fixed the issue for me.

**Comment by anmol26s** [comment] 2018-12-10 23:09
Probably fixed by upstream. Reopen if the issue is still there.

**Closed by anmol26s** 2018-12-10 23:09 UTC
